name: 6) Deploy Internal Sample Workload 
permissions:
      id-token: write
      contents: read
on:
  workflow_run:
    workflows: [5) Configure AKS]
    types:
      - completed
  workflow_dispatch:

env:
  EMAIL: ${{ secrets.EMAIL }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AKSESLZ_PATH : ./akselz
  DEPLOYMENT_LOCATION: eastus
  RESOURCE_GROUP: ESLZ-SPOKE
  CLUSTER_NAME: eslzakscluster
  AGENT_POOL_NAME: eslzacragentpool
  SPOKE_VNET_NAME: VNet-SPOKE
  SPOKE_SUBNET_NAME: servicespe
  AGENT_POOL_TIER: S2
  AGENT_POOL_COUNT: 1
  AKS_ADMINS_GROUP_NAME: AKS Admins
  MONGO_DB_USER: mongouser
  
jobs:
  on-success:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted
    name: 'Deploy Internal Sample Workload'
    steps:
    
      - name: Create Random MongoDB password for this app
        run: | 
            echo 'MongoDB_Password='$(uuidgen) >> $GITHUB_ENV

      - name: Find ACR Name
        uses: Azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
          
            az login --identity # Login as the VM's Managed Identity
            ACR_NAME="$(az acr list --resource-group ${{ env.RESOURCE_GROUP }} --query [0].name -o tsv)"
            echo 'ACR_NAME='$ACR_NAME >> $GITHUB_ENV

      - name: Create Agent Pool
        uses: Azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
          
            az acr agentpool create --registry ${{ env.ACR_NAME }} --name ${{ env.AGENT_POOL_NAME }} --tier ${{ env.AGENT_POOL_TIER }} --count ${{ env.AGENT_POOL_COUNT }} --subnet-id ${{ env.SUBNET_ID }}

      - name: Find KeyVault Name
        uses: Azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
          
            KEYVAULT_NAME=$(az keyvault list --resource-group ${{ env.RESOURCE_GROUP }} --query [0].name -o tsv)
            echo 'KEYVAULT_NAME='$KEYVAULT_NAME >> $GITHUB_ENV

      - name: Find AKS ID
        uses: Azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
          
            AKS_ID="$(az aks list --resource-group ${{ env.RESOURCE_GROUP }} --query [0].id -o tsv)"
            echo 'AKS_ID='$AKS_ID >> $GITHUB_ENV
            
      - name: Get the clientId of the azure-keyvault-secrets-provider User Assigned Managed Identity
        uses: Azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |

            azureKeyvaultSecretsProviderUserAssignedManagedIdentityClientId="$(az aks addon show --name ${{ env.CLUSTER_NAME }} --resource-group ${{ env.RESOURCE_GROUP }} -a azure-keyvault-secrets-provider --query identity.clientId -o tsv)"
            echo 'azureKeyvaultSecretsProviderUserAssignedManagedIdentityClientId='$azureKeyvaultSecretsProviderUserAssignedManagedIdentityClientId >> $GITHUB_ENV
            
      - name: Store MongoDb Connection String in KeyVault using the Jumpbox VMs system-assigned managed identity
        uses: Azure/CLI@v1
        if: ${{ env.KEYVAULT_NAME != '' && env.AGENT_POOL != '' }}
        with:
          azcliversion: latest
          inlineScript: |
          
            az keyvault secret set --name mongodburi --vault-name ${{ env.KEYVAULT_NAME }} --value "mongodb://${{ env.MONGO_DB_USER }}:${{ env.MongoDB_Password }}@ratings-mongodb.ratingsapp:27017/ratingsdb"

      - name: Login to ACR Using Managed Identity
        uses: Azure/CLI@v1
        if: ${{ env.ACR_NAME != '' && env.AGENT_POOL != '' }}
        with:
          azcliversion: latest
          inlineScript: |
          
            az login --identity
            az acr login --name ${{ env.ACR_NAME }} --expose-token

      - name: Build and Push web app using the ACR and agent pool
        uses: Azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
          
            az acr build --no-logs --agent-pool ${{ env.AGENT_POOL_NAME }} --image ratings-web:v1 --registry ${{ env.ACR_NAME }} --file Dockerfile https://github.com/MicrosoftDocs/mslearn-aks-workshop-ratings-web.git#master

      - name: Build and Push api app using the ACR and agent pool
        uses: Azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
          
            az acr build --no-logs --agent-pool ${{ env.AGENT_POOL_NAME }} --image ratings-api:v1 --registry ${{ env.ACR_NAME }} --file Dockerfile https://github.com/ivegamsft/mslearn-aks-workshop-ratings-api.git#master

      - name: Check out this Repo
        uses: actions/checkout@v2
        with:
          path: ${{ env.AKSESLZ_PATH }}
          
      - name: Edit local copy of YAML
        if: ${{ env.AGENT_POOL != '' && env.ACR_NAME != '' && env.KEYVAULT_NAME != '' && env.AZURE_TENANT_ID != '' && env.EMAIL != '' }}
        run: |
          cd $GITHUB_WORKSPACE/${{ env.AKSESLZ_PATH }}/Scenarios/AKS-Secure-Baseline-PrivateCluster/Apps/RatingsApp
          find . -type f -exec sed -i 's/<keyvault>/${{ env.KEYVAULT_NAME }}/g' {} +
          find . -type f -exec sed -i 's/<client id>/${{ env.azureKeyvaultSecretsProviderUserAssignedManagedIdentityClientId }}/g' {} +
          find . -type f -exec sed -i 's/<tenant id>/${{ env.AZURE_TENANT_ID }}/g' {} +
          find . -type f -exec sed -i 's/<acr name>/${{ env.ACR_NAME }}/g' {} +
          find . -type f -exec sed -i 's/<your e-mail here>/${{ env.EMAIL }}/g' {} +

      - name: Deploy NGINX
        uses: Azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
          
            az login --identity            
            az aks command invoke --resource-group ${{ env.RESOURCE_GROUP }} --name ${{ env.CLUSTER_NAME }} --command "helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx && helm repo update && helm install ingress-nginx ingress-nginx/ingress-nginx --set controller.service.annotations.'service\.beta\.kubernetes\.io/azure-load-balancer-health-probe-request-path=/healthz' -f internal-ingress.yaml" --file $GITHUB_WORKSPACE/${{ env.AKSESLZ_PATH }}/Scenarios/AKS-Secure-Baseline-PrivateCluster/Apps/RatingsApp/internal-ingress.yaml

      - name: Deploy Web App and API app
        uses: Azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |

            az login --identity
            
            az aks command invoke --resource-group ${{ env.RESOURCE_GROUP }} --name ${{ env.CLUSTER_NAME }} --command "kubectl create namespace ratingsapp"
            az aks command invoke --resource-group ${{ env.RESOURCE_GROUP }} --name ${{ env.CLUSTER_NAME }} --command "helm repo add bitnami https://charts.bitnami.com/bitnami && helm install ratings bitnami/mongodb --namespace ratingsapp --create-namespace --set image.tag=5.0.14-debian-11-r9,auth.username=${{ env.MONGO_DB_USER }},auth.password=${{ env.MongoDB_Password }},auth.database=ratingsdb"
            az aks command invoke --resource-group ${{ env.RESOURCE_GROUP }} --name ${{ env.CLUSTER_NAME }} --command "kubectl apply -f api-secret-provider-class.yaml -n ratingsapp" --file $GITHUB_WORKSPACE/${{ env.AKSESLZ_PATH }}/Scenarios/AKS-Secure-Baseline-PrivateCluster/Apps/RatingsApp/api-secret-provider-class.yaml
            az aks command invoke --resource-group ${{ env.RESOURCE_GROUP }} --name ${{ env.CLUSTER_NAME }} --command "kubectl apply -f 1-ratings-api-deployment.yaml -n ratingsapp" --file $GITHUB_WORKSPACE/${{ env.AKSESLZ_PATH }}/Scenarios/AKS-Secure-Baseline-PrivateCluster/Apps/RatingsApp/1-ratings-api-deployment.yaml
            az aks command invoke --resource-group ${{ env.RESOURCE_GROUP }} --name ${{ env.CLUSTER_NAME }} --command "kubectl apply -f 2-ratings-api-service.yaml -n ratingsapp" --file $GITHUB_WORKSPACE/${{ env.AKSESLZ_PATH }}/Scenarios/AKS-Secure-Baseline-PrivateCluster/Apps/RatingsApp/2-ratings-api-service.yaml
            az aks command invoke --resource-group ${{ env.RESOURCE_GROUP }} --name ${{ env.CLUSTER_NAME }} --command "kubectl apply -f 3a-ratings-web-deployment.yaml -n ratingsapp" --file $GITHUB_WORKSPACE/${{ env.AKSESLZ_PATH }}/Scenarios/AKS-Secure-Baseline-PrivateCluster/Apps/RatingsApp/3a-ratings-web-deployment.yaml
            az aks command invoke --resource-group ${{ env.RESOURCE_GROUP }} --name ${{ env.CLUSTER_NAME }} --command "kubectl apply -f 4-ratings-web-service.yaml -n ratingsapp" --file $GITHUB_WORKSPACE/${{ env.AKSESLZ_PATH }}/Scenarios/AKS-Secure-Baseline-PrivateCluster/Apps/RatingsApp/4-ratings-web-service.yaml
            az aks command invoke --resource-group ${{ env.RESOURCE_GROUP }} --name ${{ env.CLUSTER_NAME }} --command "kubectl apply -f 5b-http-ratings-web-ingress.yaml -n ratingsapp" --file $GITHUB_WORKSPACE/${{ env.AKSESLZ_PATH }}/Scenarios/AKS-Secure-Baseline-PrivateCluster/Apps/RatingsApp/5b-http-ratings-web-ingress.yaml
   
      - name: Remove Agent Pool to save $
        uses: Azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
          
               az acr agentpool delete -n ${{ env.AGENT_POOL_NAME }} -r ${{ env.ACR_NAME }} --yes
   
      - name: Log out as per best practices for self-hosted runners (https://github.com/Azure/login#az-logout-and-security-hardening)
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az logout
            az cache purge
            az account clear

